[build]
  command = "pip install -r requirements.txt && pip install flask-cors"
  publish = "/"

[dev]
  command = "python database.py"
  port = 5000
  publish = "/"



[[redirects]]
from = "/*"
to = "main.html"
status = 200
