[build]
  command = "pip install -r requirements.txt"
  publish = "/"

[dev]
  command = "python app.py"
  port = 5000
  publish = "/"



[[redirects]]
from = "/*"
to = "main.html"
status = 200
